# Form implementation generated from reading ui file 'c:\Users\Luiz\PyQT-luiz_pedro\views\ui\self.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_AboutDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("AboutDialog")
        self.resize(430, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(430, 250))
        self.setMaximumSize(QtCore.QSize(430, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Luiz\\PyQT-luiz_pedro\\views\\ui\\../styles/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.okBtn = QtWidgets.QDialogButtonBox(parent=self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.okBtn.setFont(font)
        self.okBtn.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okBtn.setObjectName("okBtn")
        self.verticalLayout_2.addWidget(self.okBtn)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.okBtn.accepted.connect(self.close)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("AboutDialog", "Sobre"))
        self.label.setText(_translate("AboutDialog", "<html><head/><body><p align=\"justify\">Este é um programa desenvolvido como trabalho de conclusão de curso na Universidade Federal Fluminense, na área de Ciências da Computação. O objetivo do projeto foi criar uma interface para o software FarmacIA, utilizando o framework QT6. O trabalho foi realizado originalmente pelos orientandos Luiz Guilherme Madruga Nunes de Faria e Pedro Ascar Rangel da Fonseca, sob a supervisão do professor Altobelli de Brito Mantuan.</p><p align=\"justify\">Altobelli de Brito Mantuan: <a href=\"https://github.com/altobelli\"><span style=\" text-decoration: underline; color:#20afde;\">https://github.com/altobelli<br/></span></a>Luiz Guilherme Madruga N. de Faria: <a href=\"https://github.com/lgmadruga\"><span style=\" text-decoration: underline; color:#20afde;\">https://github.com/lgmadruga</span></a><br/>Pedro Ascar Rangel da Fonseca: <a href=\"https://github.com/Pedroascar\"><span style=\" text-decoration: underline; color:#20afde;\">https://github.com/Pedroascar</span></a></p></body></html>"))

    def close(self):
        self.accept()